apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    component: postgres-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-keycloak
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      component: postgres-pv
