apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  opensearch.yml: |
    cluster.name: os-cluster
    node.master: true
    node.data: true
    network.host: 0.0.0.0
    discovery.seed_hosts: opensearch-master
    cluster.initial_master_nodes: ${node.name}

    plugins.security.allow_unsafe_democertificates: true
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/ca.pem
    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false

    plugins.security.ssl.transport.pemkey_filepath: certificates/os01/os01.key # relative path
    plugins.security.ssl.transport.pemcert_filepath: certificates/os01/os01.pem
    plugins.security.ssl.http.pemkey_filepath: certificates/os01/os01.key
    plugins.security.ssl.http.pemcert_filepath: certificates/os01/os01.pem

    plugins.security.authcz.admin_dn:
      - 'CN=ADMIN,O=UN,L=UN,ST=UN,C=UN'
    plugins.security.nodes_dn:
      - 'CN=os01,O=UN,L=UN,ST=UN,C=UN'
      - 'CN=os02,O=UN,L=UN,ST=UN,C=UN'
      - 'CN=os03,O=UN,L=UN,ST=UN,C=UN'
